map_type: costmap
#origin_z: 0.21
z_resolution: 1
z_voxels: 2
# Indicates the transformation frame of the robotâ€™s base link.
robot_base_frame: /base_link # Default.
# The frequency in Hz for the map to be updated.
update_frequency: 10.0 # Default.
# The frequency in Hz for the map to be publish display information.
publish_frequency: 5.0
# Specifies the delay in transform (tf) data that is tolerable in seconds.
transform_tolerance: 0.5

obstacle_range: 3.5
raytrace_range: 4.0

publish_voxel_map: false
meter_scoring: true

# When you want a most precise representation of your robot, you have to comment the robot_radius parameter and create a custom footprint, considering [0, 0] as the center of your robot.
footprint: [[-0.3,-0.275],[-0.3,0.275], [0.3, 0.275], [0.3,-0.275]]
# Summed at each of the footprint points, both at the x and y coordinates.
footprint_padding: 0.1

plugins:
  - {name: traversability_layer, type: "traversability_layer::TraversabilityLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

inflater_layer:
 inflation_radius: 0.15
